# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('updates', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='drawings/')),
                ('collectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('promptNum', models.IntegerField()),
                ('collectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Collection')),
            ],
        ),
    ]
