# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='numPrompts',
            field=models.IntegerField(default=5),
        ),
    ]
