# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_collection_numprompts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prompt',
            unique_together=set([('collectionId', 'promptNum')]),
        ),
    ]
