# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170429_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='collectionId',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='collectionId',
            new_name='collection',
        ),
        migrations.AlterUniqueTogether(
            name='prompt',
            unique_together=set([('collection', 'promptNum')]),
        ),
    ]
