# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170430_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/'),
        ),
    ]
