# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170430_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='likes',
        ),
        migrations.AlterField(
            model_name='drawing',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
