# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170430_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
