# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170430_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
    ]
